
import { GoogleGenAI } from "@google/genai";

const getAIClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
};

export const generateVisualFromContext = async (
  selectedText: string,
  fullContext?: string
): Promise<{ imageUrl: string; explanation: string }> => {
  const ai = getAIClient();
  
  // Model selection: gemini-2.5-flash-image is best for fast, general image generation
  const modelName = 'gemini-2.5-flash-image';
  
  const prompt = `
    Task: Create a highly accurate educational diagram, conceptual illustration, or visual scene that explains the following specific text within the context of the provided surrounding information.
    
    SELECTED TEXT: "${selectedText}"
    ${fullContext ? `DOCUMENT CONTEXT: "${fullContext.substring(0, 1000)}..."` : ''}
    
    STYLE REQUIREMENTS:
    - Professional, clear, and educational.
    - If it's a scientific/academic concept, generate a clean technical diagram or infographic.
    - If it's a fictional scene, generate a vivid, contextual illustration.
    - If it's a business model, generate a logical flowchart or relationship graph.
    - Ensure visual labels are readable or represent the concepts clearly.
    - Minimalist background, high contrast for focus.
  `;

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    let imageUrl = '';
    let explanation = '';

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
      } else if (part.text) {
        explanation += part.text;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return { imageUrl, explanation };
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};
